language: php

php:
  - 5.2
  - 5.3
  - 5.4

before_script:
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - mv ../cakephp-codesniffer ../CakePHP && cd ../CakePHP

script:
  - phpunit tests

notifications:
  email: false